# Enable Trusty dist, Standard is ancient.
dist: trusty
# Enable C++ support
language:
  - c
  - cpp
# # Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build && cd build
  - cmake -DBUILD_STG=ON -DBUILD_SGCONF=ON -DBUILD_RSCRIPTD=ON -DBUILD_SGAUTH=ON -DBUILD_ALL_MODS=ON -DBUILD_TESTS=ON ..
  - make
